language: php
php:
  - 5.6

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit

after_success:
  # - npm run codecov
  # - bash <(curl -s https://codecov.io/bash)
